data<-read.table("results.dat",header=T)
attach(data)
head(data)

#yl <- range(c(emi_mar_shuf_m+emi_mar_shuf_sd,
#              emi_mar_shuf_m-emi_mar_shuf_sd,
#              emi_mar_noshuf_m+emi_mar_noshuf_sd,
#              emi_mar_noshuf_m-emi_mar_noshuf_sd))

yl <- c(0,1)

lcex <- 1.5
acex <- 1.75
pc<-1.75
ln<-0.05

postscript(file="figure2.eps",horizontal=F,width=8,height=8,paper="special",pointsize=12,title="Kubisch et al. - Figure 2")

par(mfrow=c(2,2))
par(mar=c(5.5,1,1,.5))
par(oma=c(0,5,2,1))

plot(1,1,type="n",ylab="",xlab="",main="",xaxt="n",ylim=yl,xlim=c(0.5,3.5),bty="l",cex.lab=lcex+0.25,cex.axis=acex)
axis(side=1,at=c(1,2,3),labels=c("50","100","150"),cex.axis=acex)
mtext(side=1,expression(paste("carrying capacity (K)")),cex=lcex,line=3.5)
scen<-c("K_50","mu_03","K_150")
#noshuf_ms <-c(emi_mar_noshuf_m[exps==scen[1]],emi_mar_noshuf_m[exps==scen[2]],emi_mar_noshuf_m[exps==scen[3]])
#noshuf_sds<-c(emi_mar_noshuf_sd[exps==scen[1]],emi_mar_noshuf_sd[exps==scen[2]],emi_mar_noshuf_sd[exps==scen[3]])
#shuf_ms   <-c(emi_mar_shuf_m[exps==scen[1]],emi_mar_shuf_m[exps==scen[2]],emi_mar_shuf_m[exps==scen[3]])
#shuf_sds  <-c(emi_mar_shuf_sd[exps==scen[1]],emi_mar_shuf_sd[exps==scen[2]],emi_mar_shuf_sd[exps==scen[3]])
emi_ms <- c(emi_diff_m[exps==scen[1]],emi_diff_m[exps==scen[2]],emi_diff_m[exps==scen[3]])
emi_q025s <- c(emi_diff_q025[exps==scen[1]],emi_diff_q025[exps==scen[2]],emi_diff_q025[exps==scen[3]])
emi_q075s <- c(emi_diff_q075[exps==scen[1]],emi_diff_q075[exps==scen[2]],emi_diff_q075[exps==scen[3]])
velo_ms <- c(velo_diff_m[exps==scen[1]],velo_diff_m[exps==scen[2]],velo_diff_m[exps==scen[3]])
velo_q025s <- c(velo_diff_q025[exps==scen[1]],velo_diff_q025[exps==scen[2]],velo_diff_q025[exps==scen[3]])
velo_q075s <- c(velo_diff_q075[exps==scen[1]],velo_diff_q075[exps==scen[2]],velo_diff_q075[exps==scen[3]])
points(emi_ms~c(1:3),type="b",lwd=1.5,pch=16,cex=pc,col="black",lty=2)
#arrows(c(1:3),emi_q025s,c(1:3),emi_q075s,angle=90,code=3,length=ln,lwd=1.5)
points(velo_ms~c(1:3),type="b",lwd=1.5,pch=17,cex=pc*1.25,col="grey50",lty=2)
#arrows(c(1:3),velo_q025s,c(1:3),velo_q075s,angle=90,code=3,length=ln,lwd=1.5,col="grey50")
text(0.65,1.05,"A",cex=lcex*1.5,xpd=T)

legend("topleft",lwd=c(1.5,1.5),col=c("black","grey50"),pch=c(16,17),c("emigration rate","expansion speed"),bty="n",cex=1.5,pt.cex=c(1.5,1.75))

plot(1,1,type="n",xlab="",ylab="",main="",xaxt="n",ylim=yl,xlim=c(0.5,3.5),bty="l",cex.lab=lcex,cex.axis=acex,yaxt="n")
axis(side=1,at=c(1,2,3),labels=c("0.25","0.5","0.75"),cex.axis=acex)
scen<-c("sigma_025","mu_03","sigma_075")
mtext(side=1,expression(paste("environmental stochasticity (",sigma,")",sep="")),cex=lcex,line=3.5)
#noshuf_ms <-c(emi_mar_noshuf_m[exps==scen[1]],emi_mar_noshuf_m[exps==scen[2]],emi_mar_noshuf_m[exps==scen[3]])
#noshuf_sds<-c(emi_mar_noshuf_sd[exps==scen[1]],emi_mar_noshuf_sd[exps==scen[2]],emi_mar_noshuf_sd[exps==scen[3]])
#shuf_ms   <-c(emi_mar_shuf_m[exps==scen[1]],emi_mar_shuf_m[exps==scen[2]],emi_mar_shuf_m[exps==scen[3]])
#shuf_sds  <-c(emi_mar_shuf_sd[exps==scen[1]],emi_mar_shuf_sd[exps==scen[2]],emi_mar_shuf_sd[exps==scen[3]])
emi_ms <- c(emi_diff_m[exps==scen[1]],emi_diff_m[exps==scen[2]],emi_diff_m[exps==scen[3]])
emi_q025s <- c(emi_diff_q025[exps==scen[1]],emi_diff_q025[exps==scen[2]],emi_diff_q025[exps==scen[3]])
emi_q075s <- c(emi_diff_q075[exps==scen[1]],emi_diff_q075[exps==scen[2]],emi_diff_q075[exps==scen[3]])
velo_ms <- c(velo_diff_m[exps==scen[1]],velo_diff_m[exps==scen[2]],velo_diff_m[exps==scen[3]])
velo_q025s <- c(velo_diff_q025[exps==scen[1]],velo_diff_q025[exps==scen[2]],velo_diff_q025[exps==scen[3]])
velo_q075s <- c(velo_diff_q075[exps==scen[1]],velo_diff_q075[exps==scen[2]],velo_diff_q075[exps==scen[3]])
points(emi_ms~c(1:3),type="b",lwd=1.5,pch=16,cex=pc,col="black",lty=2)
#arrows(c(1:3),emi_q025s,c(1:3),emi_q075s,angle=90,code=3,length=ln,lwd=1.5)
points(velo_ms~c(1:3),type="b",lwd=1.5,pch=17,cex=pc*1.25,col="grey50",lty=2)
#arrows(c(1:3),velo_q025s,c(1:3),velo_q075s,angle=90,code=3,length=ln,lwd=1.5,col="grey50")
text(0.65,1.05,"B",cex=lcex*1.5,xpd=T)

plot(1,1,type="n",xlab="",ylab="",main="",xaxt="n",ylim=yl,xlim=c(0.5,3.5),bty="l",cex.lab=lcex,cex.axis=acex)
axis(side=1,at=c(1,2,3),labels=c("1","2","3"),cex.axis=acex)
mtext(side=1,expression(paste("per capita growth rate (",lambda,")",sep="")),cex=lcex,line=3.5)
scen<-c("lambda_15","mu_03","lambda_3")
#noshuf_ms <-c(emi_mar_noshuf_m[exps==scen[1]],emi_mar_noshuf_m[exps==scen[2]],emi_mar_noshuf_m[exps==scen[3]])
#noshuf_sds<-c(emi_mar_noshuf_sd[exps==scen[1]],emi_mar_noshuf_sd[exps==scen[2]],emi_mar_noshuf_sd[exps==scen[3]])
#shuf_ms   <-c(emi_mar_shuf_m[exps==scen[1]],emi_mar_shuf_m[exps==scen[2]],emi_mar_shuf_m[exps==scen[3]])
#shuf_sds  <-c(emi_mar_shuf_sd[exps==scen[1]],emi_mar_shuf_sd[exps==scen[2]],emi_mar_shuf_sd[exps==scen[3]])
emi_ms <- c(emi_diff_m[exps==scen[1]],emi_diff_m[exps==scen[2]],emi_diff_m[exps==scen[3]])
emi_q025s <- c(emi_diff_q025[exps==scen[1]],emi_diff_q025[exps==scen[2]],emi_diff_q025[exps==scen[3]])
emi_q075s <- c(emi_diff_q075[exps==scen[1]],emi_diff_q075[exps==scen[2]],emi_diff_q075[exps==scen[3]])
velo_ms <- c(velo_diff_m[exps==scen[1]],velo_diff_m[exps==scen[2]],velo_diff_m[exps==scen[3]])
velo_q025s <- c(velo_diff_q025[exps==scen[1]],velo_diff_q025[exps==scen[2]],velo_diff_q025[exps==scen[3]])
velo_q075s <- c(velo_diff_q075[exps==scen[1]],velo_diff_q075[exps==scen[2]],velo_diff_q075[exps==scen[3]])
points(emi_ms~c(1.5,2,3),type="b",lwd=1.5,pch=16,cex=pc,col="black",lty=2)
#arrows(c(1.5,2,3),emi_q025s,c(1:3),emi_q075s,angle=90,code=3,length=ln,lwd=1.5)
points(velo_ms~c(1.5,2,3),type="b",lwd=1.5,pch=17,cex=pc*1.25,col="grey50",lty=2)
#arrows(c(1.5,2,3),velo_q025s,c(1:3),velo_q075s,angle=90,code=3,length=ln,lwd=1.5,col="grey50")
text(0.65,1.05,"C",cex=lcex*1.5,xpd=T)

plot(1,1,type="n",xlab="",ylab="",main="",xaxt="n",ylim=yl,xlim=c(0.5,3.5),bty="l",cex.lab=lcex,cex.axis=acex,yaxt="n")
axis(side=1,at=c(1,2,3),labels=c("0.15","0.3","0.45"),cex.axis=acex)
mtext(side=1,expression(paste("dispersal mortality (",mu,")",sep="")),cex=lcex,line=3.5)
scen<-c("mu_015","mu_03","mu_045")
#noshuf_ms <-c(emi_mar_noshuf_m[exps==scen[1]],emi_mar_noshuf_m[exps==scen[2]],emi_mar_noshuf_m[exps==scen[3]])
#noshuf_sds<-c(emi_mar_noshuf_sd[exps==scen[1]],emi_mar_noshuf_sd[exps==scen[2]],emi_mar_noshuf_sd[exps==scen[3]])
#shuf_ms   <-c(emi_mar_shuf_m[exps==scen[1]],emi_mar_shuf_m[exps==scen[2]],emi_mar_shuf_m[exps==scen[3]])
#shuf_sds  <-c(emi_mar_shuf_sd[exps==scen[1]],emi_mar_shuf_sd[exps==scen[2]],emi_mar_shuf_sd[exps==scen[3]])
emi_ms <- c(emi_diff_m[exps==scen[1]],emi_diff_m[exps==scen[2]],emi_diff_m[exps==scen[3]])
emi_q025s <- c(emi_diff_q025[exps==scen[1]],emi_diff_q025[exps==scen[2]],emi_diff_q025[exps==scen[3]])
emi_q075s <- c(emi_diff_q075[exps==scen[1]],emi_diff_q075[exps==scen[2]],emi_diff_q075[exps==scen[3]])
velo_ms <- c(velo_diff_m[exps==scen[1]],velo_diff_m[exps==scen[2]],velo_diff_m[exps==scen[3]])
velo_q025s <- c(velo_diff_q025[exps==scen[1]],velo_diff_q025[exps==scen[2]],velo_diff_q025[exps==scen[3]])
velo_q075s <- c(velo_diff_q075[exps==scen[1]],velo_diff_q075[exps==scen[2]],velo_diff_q075[exps==scen[3]])
points(emi_ms~c(1:3),type="b",lwd=1.5,pch=16,cex=pc,col="black",lty=2)
#arrows(c(1:3),emi_q025s,c(1:3),emi_q075s,angle=90,code=3,length=ln,lwd=1.5)
points(velo_ms~c(1:3),type="b",lwd=1.5,pch=17,cex=pc*1.25,col="grey50",lty=2)
#arrows(c(1:3),velo_q025s,c(1:3),velo_q075s,angle=90,code=3,length=ln,lwd=1.5,col="grey50")
text(0.65,1.05,"D",cex=lcex*1.5,xpd=T)

title(ylab=expression(paste("relative contribution of kin competition (",Delta[r],")")),cex.lab=lcex*1.5,outer=T)

dev.off()